// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGey2NiK1wWnvlUfeE9TfVq17FN9tSVvE',
    appId: '1:35278179089:web:af1f8179764a5721495ab0',
    messagingSenderId: '35278179089',
    projectId: 'ecomanga-6ce5c',
    authDomain: 'ecomanga-6ce5c.firebaseapp.com',
    storageBucket: 'ecomanga-6ce5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpf1MMuahiCQXhoTnc_7tCvAV9PauVde8',
    appId: '1:35278179089:android:0a7704de2744e369495ab0',
    messagingSenderId: '35278179089',
    projectId: 'ecomanga-6ce5c',
    storageBucket: 'ecomanga-6ce5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_HVBVvfTwWKrxzDBSPPH_ocojmcF_CU',
    appId: '1:35278179089:ios:b34ee9bd0963cf58495ab0',
    messagingSenderId: '35278179089',
    projectId: 'ecomanga-6ce5c',
    storageBucket: 'ecomanga-6ce5c.firebasestorage.app',
    iosBundleId: 'com.eco.ecomanga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_HVBVvfTwWKrxzDBSPPH_ocojmcF_CU',
    appId: '1:35278179089:ios:b34ee9bd0963cf58495ab0',
    messagingSenderId: '35278179089',
    projectId: 'ecomanga-6ce5c',
    storageBucket: 'ecomanga-6ce5c.firebasestorage.app',
    iosBundleId: 'com.eco.ecomanga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGey2NiK1wWnvlUfeE9TfVq17FN9tSVvE',
    appId: '1:35278179089:web:d7a99d562b8f450e495ab0',
    messagingSenderId: '35278179089',
    projectId: 'ecomanga-6ce5c',
    authDomain: 'ecomanga-6ce5c.firebaseapp.com',
    storageBucket: 'ecomanga-6ce5c.firebasestorage.app',
  );

}