List<String> affirmations = [
  'Learn as if you will live forever, live like you will die tomorrow',
  'You are capable of amazing things.',
  'Positivity is a choice.',
  'You are stronger than you think.',
  'Believe in yourself and all that you are.',
  'You are enough just as you are.',
  'Embrace the glorious mess that you are.',
  'You are in charge of your happiness.',
  'Difficult roads often lead to beautiful destinations.',
  'You are capable of achieving great things.',
  'Be a voice, not an echo.',
  'Success is the sum of small efforts, repeated day in and day out.',
  'You have the power to create change.',
  'You are brave, bold, and beautiful.',
  'Your potential is endless.',
  'Start where you are. Use what you have. Do what you can.',
  'Every day is a second chance.',
  'Your only limit is your mind.',
  'Dream big. Work hard. Stay focused.',
  'You are worthy of all the good things that happen to you.',
  'Change your thoughts and you change your world.',
  'What you get by achieving your goals is not as important as what you become by achieving your goals.',
  'Only you can control your future.',
  'It always seems impossible until it is done.',
  'Set your goals high, and do not stop till you get there.',
  'You do not find the happy life. You make it.',
  'The most wasted of days is one without laughter.',
  'You must do the things you think you cannot do.',
  'It is never too late to be what you might have been.',
  'You get what you give.',
  'Some people look for a beautiful place. Others make a place beautiful.',
  'Happiness often sneaks in through a door you didn’t know you left open.',
  'Happiness is not by chance, but by choice.',
  'Life changes very quickly, in a very positive way, if you let it.',
  'Keep your face always toward the sunshine, and shadows will fall behind you.',
  'Be the change that you wish to see in the world.',
  'No matter what people tell you, words and ideas can change the world.',
  'Each day provides its own gifts.',
  'With the new day comes new strength and new thoughts.',
  'You must be the change you wish to see in the world.',
  'The best time to plant a tree was 20 years ago. The second best time is now.',
  'Everything you can imagine is real.',
  'Do what you can, with what you have, where you are.',
  'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
  'Limit your "always" and your "nevers".',
  'Nothing is impossible. The word itself says "I’m possible!"',
  'You are never too old to set another goal or to dream a new dream.',
  'Try to be a rainbow in someone’s cloud.',
  'You do not find the happy life. You make it.',
  'Inspiration comes from within yourself. One has to be positive. When you are positive, good things happen.',
  'Sometimes you will never know the value of a moment, until it becomes a memory.',
  'The bad news is time flies. The good news is you’re the pilot.',
  'Spread love everywhere you go.',
  'Don’t wait. The time will never be just right.',
  'Life is what we make it, always has been, always will be.',
  'You must expect great things of yourself before you can do them.',
  'To be the best, you must be able to handle the worst.',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  'Light tomorrow with today.',
  'The only journey is the one within.',
  'Life’s most persistent and urgent question is, "What are you doing for others?"',
  'Believe you can and you’re halfway there.',
  'Act as if what you do makes a difference. It does.',
  'Success is not final, failure is not fatal: it is the courage to continue that counts.',
  'Never bend your head. Always hold it high. Look the world straight in the eye.',
  'What you get by achieving your goals is not as important as what you become by achieving your goals.',
  'When you have a dream, you have got to grab it and never let go.',
  'I can and I will. Watch me.',
  'We generate fears while we sit. We overcome them by action.',
  'Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.',
  'The only limit to our realization of tomorrow is our doubts today.',
  'Life is 10% what happens to us and 90% how we react to it.',
  'Do not wait to strike till the iron is hot; but make it hot by striking.',
  'Whether you think you can or think you can’t, you’re right.',
  'Action is the foundational key to all success.',
  'To accomplish great things, we must not only act, but also dream, not only plan, but also believe.',
  'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.',
  'You don’t have to be great to start, but you have to start to be great.',
  'The best revenge is massive success.',
  'Only put off until tomorrow what you are willing to die having left undone.',
  'You don’t have to see the whole staircase, just take the first step.',
  'Failure will never overtake me if my determination to succeed is strong enough.',
  'It’s not whether you get knocked down. It’s whether you get up.',
  'Your true success in life begins only when you make the commitment to become excellent at what you do.',
  'Believe in yourself! Have faith in your abilities!',
  'A creative man is motivated by the desire to achieve, not by the desire to beat others.',
  'A real decision is measured by the fact that you’ve taken a new action. If there’s no action, you haven’t truly decided.',
  'Success does not consist in never making mistakes but in never making the same one a second time.',
  'I do not want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well.',
  'You must not only aim right, but draw the bow with all your might.',
  'Hope is a waking dream.',
  'Your big opportunity may be right where you are now.',
  'A champion is defined not by their wins but by how they can recover when they fall.'
];
