// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdnYxJWLjvhly3BqxSJXW3988LVm9rx0',
    appId: '1:345472577:web:f0c84af34df9d76fd610c0',
    messagingSenderId: '345472577',
    projectId: 'affirmationapp-42aae',
    authDomain: 'affirmationapp-42aae.firebaseapp.com',
    storageBucket: 'affirmationapp-42aae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5oI_ALa6vjmAJuBwjrhs221Qj_nJKEyM',
    appId: '1:345472577:android:0d1f0da5d695592cd610c0',
    messagingSenderId: '345472577',
    projectId: 'affirmationapp-42aae',
    storageBucket: 'affirmationapp-42aae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5nViMG6a5Ay9078Rz8TOOf6FZrqSfl98',
    appId: '1:345472577:ios:d5feb0665cec5329d610c0',
    messagingSenderId: '345472577',
    projectId: 'affirmationapp-42aae',
    storageBucket: 'affirmationapp-42aae.appspot.com',
    androidClientId: '345472577-br4kv65m5i8v7lh3u04etg0o5vmggq2s.apps.googleusercontent.com',
    iosClientId: '345472577-bam27v886u59a36qllkmsrjlej4fc820.apps.googleusercontent.com',
    iosBundleId: 'com.example.affirmationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5nViMG6a5Ay9078Rz8TOOf6FZrqSfl98',
    appId: '1:345472577:ios:d5feb0665cec5329d610c0',
    messagingSenderId: '345472577',
    projectId: 'affirmationapp-42aae',
    storageBucket: 'affirmationapp-42aae.appspot.com',
    androidClientId: '345472577-br4kv65m5i8v7lh3u04etg0o5vmggq2s.apps.googleusercontent.com',
    iosClientId: '345472577-bam27v886u59a36qllkmsrjlej4fc820.apps.googleusercontent.com',
    iosBundleId: 'com.example.affirmationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdnYxJWLjvhly3BqxSJXW3988LVm9rx0',
    appId: '1:345472577:web:1d4b2510dfc087a2d610c0',
    messagingSenderId: '345472577',
    projectId: 'affirmationapp-42aae',
    authDomain: 'affirmationapp-42aae.firebaseapp.com',
    storageBucket: 'affirmationapp-42aae.appspot.com',
  );

}