# Generated by Django 4.2.7 on 2025-07-15 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/audio/'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_participant2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post'), ('link', 'Link Post'), ('audio', 'Audio Post')], default='text', max_length=10),
        ),
        migrations.AlterModelTable(
            name='block',
            table='social_blocks',
        ),
        migrations.AlterModelTable(
            name='chat',
            table='social_chats',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='social_comments',
        ),
        migrations.AlterModelTable(
            name='commentlike',
            table='social_comment_likes',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='social_follows',
        ),
        migrations.AlterModelTable(
            name='message',
            table='social_messages',
        ),
        migrations.AlterModelTable(
            name='post',
            table='social_posts',
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='social_post_likes',
        ),
    ]
